[build]
  command = "npm run build"
  publish = "advizeapp-frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://advizeapp-0bd9740bb742.herokuapp.com"
