[build]
  base = "advizeapp-frontend"  # Ο φάκελος όπου βρίσκεται το frontend
  command = "npm run build"   # Εντολή για τη δημιουργία του frontend build
  publish = "advizeapp-frontend/build"  # Ο φάκελος που περιέχει τα static αρχεία

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://advizeapp-0bd9740bb742.herokuapp.com"
