[build]
  base = "advizeapp-frontend"  # Το σωστό base directory
  command = "npm run build"    # Εντολή κατασκευής του frontend
  publish = "build"            # Ο φάκελος που δημιουργείται από την εντολή `npm run build`
  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://advizeapp-0bd9740bb742.herokuapp.com"
