[build]
  command = "pip install -r requirements.txt && uvicorn advizeapp_backend.main:app --host=0.0.0.0 --port=$PORT"
  publish = "."

[context.production.environment]
  DATABASE_URL = "postgresql://postgres:pWYxLIDjmUkXiRiGeXljoAtJKeVWlViG@junction.proxy.rlwy.net:28163/railway"
