[build]
  base = "advizeapp-frontend"
  command = "CI= npm run build"
  publish = "build"
  

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://advizeapp-0bd9740bb742.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
